name: asood
description: A new Flutter project.

publish_to: "none"
version: 1.0.7+1014

environment:
  #sdk: '>=3.2.0-210.3.beta <4.0.0'
  sdk: '>=3.2.6 <4.0.0'
isar_version: &isar_version 3.1.0
dependencies:
  animated_bottom_navigation_bar: ^1.3.2
  bloc: ^8.1.3
  flutter_secure_storage: ^9.2.2
  cached_network_image: ^3.2.1
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  change_app_package_name: ^1.1.0
#  connectivity: ^3.0.6
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.2
  custom_map_markers: ^0.0.2+1
  equatable: ^2.0.5
  file_picker: ^8.0.0+1
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_colorpicker: ^1.0.3
  flutter_local_notifications: ^17.2.3
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_osm_plugin: ^0.70.3
  flutter_otp_text_field: ^1.1.1
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.2
  geolocator: ^10.1.0
  google_maps_flutter: ^2.1.1
  google_maps_flutter_web: ^0.4.0+5
  http: ^1.2.0
  image_picker: ^0.8.5+3
  intl: any
  intl_phone_field: ^3.2.0
  isar: 3.1.0
#  isar_flutter_libs: 3.1.0
  latlong2: ^0.9.0
  path_provider: ^2.0.8
  pin_code_fields: ^7.3.0
  smooth_page_indicator: ^1.1.0
  location: ^6.0.2
  url_launcher: ^6.0.17
  auto_route: ^7.9.2

dev_dependencies:
  build_runner: any
  auto_route_generator: ^7.3.2
  flutter_lints: ^2.0.0
  # flutter_test:
  #   sdk: flutter
  isar_generator: *isar_version

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: irs
      fonts:
        - asset: fonts/irs.ttf
    - family: yekan
      fonts:
        - asset: fonts/yekan.ttf
    - family: dastnevis
      fonts:
        - asset: fonts/dastnevis.otf
    - family: mitra
      fonts:
        - asset: fonts/mitra.ttf
    - family: nazanin
      fonts:
        - asset: fonts/nazanin.ttf
    - family: traffic
      fonts:
        - asset: fonts/traffic.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
